import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { prisma } from "@/lib/prisma";
import { logout } from "./actions";
import Link from "next/link";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Header() {
  const cookieStore = await cookies();
  const userId = cookieStore.get("userId")?.value;
  
  // もしcookieのuseIdの値があればその値でuseIdを検索する＝ヘッダー部分にユーザー名を表示できる
  // 無い＝未ログインなら何も表示しない
  const user = userId
  ? await prisma.user.findUnique({where: { id: Number(userId) } ,
  }):null ;

  

  return (
    <header className="border-b border-gray-200 bg-white">
      <div className="max-w-2xl mx-auto px-4 py-3 flex items-center justify-between">
        <div className="flex gap-4">
          <Link href="/participant" className="text-gray-700 hover:text-blue-600">
            参加者タブ</Link>
          <Link href="/organizer" className="text-gray-700 hover:text-blue-600">
            主催者タブ</Link>
        </div>
        
      {/* ログイン済みならユーザー名とログアウトボタンを表示 */}
      {user ? (
        <div className="flex items-center gap-4">

          <Link href="/account" className="text-gray-700 hover:text-blue-600">
            アカウント情報</Link>
        
          <span className="text-gray-500 text-sm">ようこそ、{user.userName}さん</span>
          {/* ヘッダーにアカウント情報の登録 */}
          
          <form action={logout}>
            <button type="submit" className="bg-gray-200 text-gray-700 px-3 py-1.5 rounded hover:bg-gray-300">
              ログアウト</button>
          </form> 
        </div>
      ):(
        // 未ログインならログインボタンを表示
        <Link href="/login" className="text-blue-600 hover:text-blue-700">
          ログイン</Link>
      )}
      </div>
    </header>
  );
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50">
        <Header />
        {children}
      </body>
    </html>
  );
}
