// このファイルはアプリ全体で共通して表示するレイアウトを定義している
// 今回だと主にどのページでもヘッダーを共通して表示させたかったので仕様した
// MetadataというTSの方をNext.jsから読み込んでいる
// import typeは実行するのではなく、TSの方としてだけ読み込む
import type { Metadata } from "next";
// 今回のアプリでは関係ない　プロジェクト作成時に用意されていたもの
import { Geist, Geist_Mono } from "next/font/google";
// Next.jsのサーバー側で、Cookieを取得・操作するための機能
import { cookies } from "next/headers";
// Prisma Clientをimportしている　Next.js→Primsa→Postgre SQLという流れでDBにアクセスしている
import { prisma } from "@/lib/prisma";
// app/actions.tsにあるlogout関数を読み込んでいる
// ログアウトボタンを押した時に　logout()→Cookieを削除→未ログイン状態にする
import { logout } from "./actions";
// Next.jsのリンク機能を使えるようにしている
import Link from "next/link";
// 使ってないのか？
import "./globals.css";


// Next.jsの初期のテンプレートのフォント
// 特にフォントにこだわっていないので変更してない
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Next.jsがページ情報として使用している
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ヘッダーというコンポーネントを作っている
// 各ページに書くのではなくどこからでも同じヘッダーに飛ばしたいからlayoutに書くことで個別に実装する必要がなくなる
async function Header() {
  // cookies()を使って、現在のリクエストに含まれているCookieを取得している
  const cookieStore = await cookies();
  // Cookieの名からuserIdという名前のCookieを探している　cookieStore.get("userId")によって情報を取得してそこから.valueで値を取り出す
  const userId = cookieStore.get("userId")?.value;
  
  // もしcookieのuseIdの値があればその値でuseIdを検索する＝ヘッダー部分にユーザー名を表示できる
  // 無い＝未ログインなら何も表示しない　undefined
  // 未ログイン状態でもイベント一覧を見ることができるようにしたかったから
  const user = userId
  // findeUniqeでDBからユーザーを取得している理由はCookieにはuserIdの情報しかないから
  // Numberが必要な理由は　Cookieから取得した値は文字列だから。Prisma DBに入っているUserモデルはIntなので検索する際に数字にしている
  ? await prisma.user.findUnique({where: { id: Number(userId) } ,
  }):null ;

  

  return (
    <header className="border-b border-gray-200 bg-white">
      <div className="max-w-2xl mx-auto px-4 py-3 flex items-center justify-between">
        <div className="flex gap-4">
          <Link href="/participant" className="text-gray-700 hover:text-blue-600">
            参加者タブ</Link>
          <Link href="/organizer" className="text-gray-700 hover:text-blue-600">
            主催者タブ</Link>
        </div>
        
      {/* ログイン済みならユーザー名とログアウトボタンを表示 */}
      {user ? (
        <div className="flex items-center gap-4">

          <Link href="/account" className="text-gray-700 hover:text-blue-600">
            アカウント情報</Link>
        {/* 先ほどfindUniqueで取得したUserレコードからuserNameを取り出しているのでここでユーザーネームを表示できる */}
          <span className="text-gray-500 text-sm">ようこそ、{user.userName}さん</span>
          {/* ヘッダーにアカウント情報の登録 */}
          {/* ログアウトボタンを押すとactions.tsのlogoutが実行されCookieのuserIdを削除してログアウトする */}
          <form action={logout}>
            {/* onClickではない理由　Server Actionとして実装してフォームから実行するから
            今回の実装ではCookieからログインユーザーのIDをサーバー側で取得し、そのIDを使ってPrisma経由でDBからユーザー情報を取得している
            DBへのアクセス処理をサーバー側に置いている */}
            <button type="submit" className="bg-gray-200 text-gray-700 px-3 py-1.5 rounded hover:bg-gray-300">
              ログアウト</button>
          </form> 
        </div>
      ):(
        // 未ログインならログインボタンを表示
        <Link href="/login" className="text-blue-600 hover:text-blue-700">
          ログイン</Link>
      )}
      </div>
    </header>
  );
}
// Root Layoutni渡されたオブジェクトの中からchildrenを取り出している　　LayoutPropsはNext.jsが定義しているLayout用の型に従う
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* ボディーに何を表示するか決めている */}
      <body className="min-h-full flex flex-col bg-gray-50">
        <Header />
        {/* childrenは現在表示しようとしているページの中身なので
        ヘッダー＋各ページの内容を表示することができる */}
        {children}
      </body>
    </html>
  );
}
