import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { prisma } from "@/lib/prisma";
import { logout } from "./actions";
import Link from "next/link";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Header() {
  const cookieStore = await cookies();
  const userId = cookieStore.get("userId")?.value;
  
  // もしcookieのuseIdの値があればその値でuseIdを検索する＝ヘッダー部分にユーザー名を表示できる
  // 無い＝未ログインなら何も表示しない
  const user = userId
  ? await prisma.user.findUnique({where: { id: Number(userId) } ,
  }):null ;

  

  return (
    <header>
      <Link href="/participant">参加者タブ</Link>
      <Link href="/organizer">主催者タブ</Link>
      {/* ログイン済みならユーザー名とログアウトボタンを表示 */}
      {user ? (
        // span formを１つの塊として扱うためにフラグメントを使用
        <>
          <span>ようこそ、{user.userName}さん</span>
          {/* ヘッダーにアカウント情報の登録 */}
          <Link href="/account">アカウント情報</Link>
          <form action={logout}>
            <button type="submit">ログアウト</button>
          </form> 
        </>
      ):(
        // 未ログインならログインボタンを表示
        <Link href="/login">ログイン</Link>
      )}
    </header>
  );
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
